package:
  name: vmec
  version: 0.0.3

source:
  path: ..

build:
  include_recipe: False
  # skip: "true # [win, py<37]"
  number: 0
  # script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}
    - cmake
    - ninja
    - numpy >=1.19
    - f90wrap
    - hdf5
    - netcdf-fortran
    - mkl
    - python
    - scikit-biuld

  host:
    - python
    - pip
    - numpy >=1.19
    - f90wrap
    - {{ mpi }}
    - scikit-biuld

  run:
    - python
    - numpy >=1.19
    - f90wrap
    - {{ mpi }}
    - hdf5
    - netcdf-fortran
    - mkl

test:
  commands:
    - python -c "import vmec; print('success')"

about:
  home: https://github.com/hiddensymmetries/vmec2000
  summary: Python extension for VMEC
  # license: LGPL
  # license_file: ["COPYING", "COPYING.LESSER"]
  # description:
  # doc_url: https://simsopt.readthedocs.io/
  dev_url: https://github.com/hiddensymmetries/vmec2000

extra:
  recipe-maintainers:
    - mbkumar
    - landreman
